services:
  caddy:
    image: caddy:2.9.1-alpine

    # If container crashes or reboots, Docker will
    # restart the container automatically. The only situation
    # where it doesn't automatically restart is when you explicitly stop it.
    restart: unless-stopped

    ports:
      # Ports for HTTP, and HTTPS.
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      # Bind mounts; so the container uses
      # our local machine's caddy file and the content
      # in our site directory, which is wher we'll be serving our stuff, but
      # of course this can be modified.
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv

      # Regular volumes for persisting important Caddy related data. Caddy will store TLS
      # certificates, private keys and other things in the data directory.
      - caddy_data:/data

      # Configuration Directory where caddy stores certain configurations on Disk. It persists the last
      # active configuration to this folder (by default).
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
