name: Node CI
on: [push]
jobs:
  build:
    # Use the OS that's currently being used
    runs-on: ${{matrix.os}}

    # Matrix strategy does a Cartesian product of all possible combinations of the defined variables
    # As a result, it's similar to a nested loop and we're iterating through each combination
    # and we're running the job for each.
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      # Here we omitted the name for the first step of giving the runner the code.
      - uses: actions/checkout@v1

      # Uses the official GitHub Action to install node JS, also specifies specific version
      - name: Use Nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Executing shell commands to run on the server
      - name: npm install, build, and test
        run: |
          npm ci 
          npm run build --if-present
          npm test
        # Sets environment variables that apply to the current step. This CI=true actually does things
        # because it makes tests complete faster.
        env:
          CI: true
